baseURL: 'https://javaalmanac.io/'
languageCode: 'en-us'
title: 'javaalmanac.io'
disableKinds: ['RSS', 'taxonomyTerm']

params:
    sourcebase: 'https://github.com/marchof/java-almanac/blob/master/site/'

deployment:
    targets:
        name: 'javaalmanac.io'
        URL: 's3://javaalmanac.io?region=us-east-1'
